# fr0g-ai-aip Configuration Example
# Copy this file to config.yaml and modify as needed

# HTTP Server Configuration
http:
  port: "8080"
  read_timeout: 30s
  write_timeout: 30s
  shutdown_timeout: 10s
  enable_tls: false
  cert_file: ""
  key_file: ""

# gRPC Server Configuration
grpc:
  port: "9090"
  max_recv_msg_size: 4194304  # 4MB
  max_send_msg_size: 4194304  # 4MB
  connection_timeout: 30s
  enable_tls: false
  cert_file: ""
  key_file: ""

# Storage Configuration
storage:
  type: "memory"  # Options: memory, file
  data_dir: "./data"  # Only used when type is "file"

# Client Configuration
client:
  type: "local"  # Options: local, rest, grpc
  server_url: "http://localhost:8080"  # Only used for rest/grpc clients
  timeout: 30s

# Security Configuration
security:
  enable_auth: false
  api_key: ""

# Logging Configuration
logging:
  level: "info"  # Options: debug, info, warn, error
  format: "text"  # Options: text, json

# Environment Variables Override Examples:
# HTTP_PORT=8080
# GRPC_PORT=9090
# STORAGE_TYPE=file
# STORAGE_DATA_DIR=/var/lib/fr0g-ai-aip
# CLIENT_TYPE=rest
# CLIENT_SERVER_URL=https://api.example.com
# SECURITY_ENABLE_AUTH=true
# SECURITY_API_KEY=your-secret-key
# LOG_LEVEL=debug
# LOG_FORMAT=json
