// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/persona.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Persona represents an AI persona with specific expertise
type Persona struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Context       map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Rag           []string               `protobuf:"bytes,6,rep,name=rag,proto3" json:"rag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Persona) Reset() {
	*x = Persona{}
	mi := &file_proto_persona_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Persona) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Persona) ProtoMessage() {}

func (x *Persona) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Persona.ProtoReflect.Descriptor instead.
func (*Persona) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{0}
}

func (x *Persona) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Persona) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Persona) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Persona) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Persona) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Persona) GetRag() []string {
	if x != nil {
		return x.Rag
	}
	return nil
}

// Request messages
type CreatePersonaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Persona       *Persona               `protobuf:"bytes,1,opt,name=persona,proto3" json:"persona,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersonaRequest) Reset() {
	*x = CreatePersonaRequest{}
	mi := &file_proto_persona_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonaRequest) ProtoMessage() {}

func (x *CreatePersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonaRequest.ProtoReflect.Descriptor instead.
func (*CreatePersonaRequest) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePersonaRequest) GetPersona() *Persona {
	if x != nil {
		return x.Persona
	}
	return nil
}

type GetPersonaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonaRequest) Reset() {
	*x = GetPersonaRequest{}
	mi := &file_proto_persona_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonaRequest) ProtoMessage() {}

func (x *GetPersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonaRequest.ProtoReflect.Descriptor instead.
func (*GetPersonaRequest) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{2}
}

func (x *GetPersonaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePersonaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePersonaRequest) Reset() {
	*x = DeletePersonaRequest{}
	mi := &file_proto_persona_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonaRequest) ProtoMessage() {}

func (x *DeletePersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonaRequest.ProtoReflect.Descriptor instead.
func (*DeletePersonaRequest) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePersonaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPersonasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonasRequest) Reset() {
	*x = ListPersonasRequest{}
	mi := &file_proto_persona_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonasRequest) ProtoMessage() {}

func (x *ListPersonasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonasRequest.ProtoReflect.Descriptor instead.
func (*ListPersonasRequest) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{4}
}

type UpdatePersonaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Persona       *Persona               `protobuf:"bytes,2,opt,name=persona,proto3" json:"persona,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePersonaRequest) Reset() {
	*x = UpdatePersonaRequest{}
	mi := &file_proto_persona_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonaRequest) ProtoMessage() {}

func (x *UpdatePersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonaRequest.ProtoReflect.Descriptor instead.
func (*UpdatePersonaRequest) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePersonaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePersonaRequest) GetPersona() *Persona {
	if x != nil {
		return x.Persona
	}
	return nil
}

// Response messages
type CreatePersonaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Persona       *Persona               `protobuf:"bytes,1,opt,name=persona,proto3" json:"persona,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePersonaResponse) Reset() {
	*x = CreatePersonaResponse{}
	mi := &file_proto_persona_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePersonaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonaResponse) ProtoMessage() {}

func (x *CreatePersonaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonaResponse.ProtoReflect.Descriptor instead.
func (*CreatePersonaResponse) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePersonaResponse) GetPersona() *Persona {
	if x != nil {
		return x.Persona
	}
	return nil
}

type GetPersonaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Persona       *Persona               `protobuf:"bytes,1,opt,name=persona,proto3" json:"persona,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonaResponse) Reset() {
	*x = GetPersonaResponse{}
	mi := &file_proto_persona_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonaResponse) ProtoMessage() {}

func (x *GetPersonaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonaResponse.ProtoReflect.Descriptor instead.
func (*GetPersonaResponse) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{7}
}

func (x *GetPersonaResponse) GetPersona() *Persona {
	if x != nil {
		return x.Persona
	}
	return nil
}

type DeletePersonaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePersonaResponse) Reset() {
	*x = DeletePersonaResponse{}
	mi := &file_proto_persona_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePersonaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonaResponse) ProtoMessage() {}

func (x *DeletePersonaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonaResponse.ProtoReflect.Descriptor instead.
func (*DeletePersonaResponse) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{8}
}

type ListPersonasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Personas      []*Persona             `protobuf:"bytes,1,rep,name=personas,proto3" json:"personas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPersonasResponse) Reset() {
	*x = ListPersonasResponse{}
	mi := &file_proto_persona_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPersonasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonasResponse) ProtoMessage() {}

func (x *ListPersonasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonasResponse.ProtoReflect.Descriptor instead.
func (*ListPersonasResponse) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{9}
}

func (x *ListPersonasResponse) GetPersonas() []*Persona {
	if x != nil {
		return x.Personas
	}
	return nil
}

type UpdatePersonaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Persona       *Persona               `protobuf:"bytes,1,opt,name=persona,proto3" json:"persona,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePersonaResponse) Reset() {
	*x = UpdatePersonaResponse{}
	mi := &file_proto_persona_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePersonaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonaResponse) ProtoMessage() {}

func (x *UpdatePersonaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_persona_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonaResponse.ProtoReflect.Descriptor instead.
func (*UpdatePersonaResponse) Descriptor() ([]byte, []int) {
	return file_proto_persona_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePersonaResponse) GetPersona() *Persona {
	if x != nil {
		return x.Persona
	}
	return nil
}

var File_proto_persona_proto protoreflect.FileDescriptor

const file_proto_persona_proto_rawDesc = "" +
	"\n" +
	"\x13proto/persona.proto\x12\apersona\"\xe2\x01\n" +
	"\aPersona\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x127\n" +
	"\acontext\x18\x05 \x03(\v2\x1d.persona.Persona.ContextEntryR\acontext\x12\x10\n" +
	"\x03rag\x18\x06 \x03(\tR\x03rag\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x14CreatePersonaRequest\x12*\n" +
	"\apersona\x18\x01 \x01(\v2\x10.persona.PersonaR\apersona\"#\n" +
	"\x11GetPersonaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x14DeletePersonaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13ListPersonasRequest\"R\n" +
	"\x14UpdatePersonaRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\apersona\x18\x02 \x01(\v2\x10.persona.PersonaR\apersona\"C\n" +
	"\x15CreatePersonaResponse\x12*\n" +
	"\apersona\x18\x01 \x01(\v2\x10.persona.PersonaR\apersona\"@\n" +
	"\x12GetPersonaResponse\x12*\n" +
	"\apersona\x18\x01 \x01(\v2\x10.persona.PersonaR\apersona\"\x17\n" +
	"\x15DeletePersonaResponse\"D\n" +
	"\x14ListPersonasResponse\x12,\n" +
	"\bpersonas\x18\x01 \x03(\v2\x10.persona.PersonaR\bpersonas\"C\n" +
	"\x15UpdatePersonaResponse\x12*\n" +
	"\apersona\x18\x01 \x01(\v2\x10.persona.PersonaR\apersona2\x94\x03\n" +
	"\x0ePersonaService\x12N\n" +
	"\rCreatePersona\x12\x1d.persona.CreatePersonaRequest\x1a\x1e.persona.CreatePersonaResponse\x12E\n" +
	"\n" +
	"GetPersona\x12\x1a.persona.GetPersonaRequest\x1a\x1b.persona.GetPersonaResponse\x12K\n" +
	"\fListPersonas\x12\x1c.persona.ListPersonasRequest\x1a\x1d.persona.ListPersonasResponse\x12N\n" +
	"\rUpdatePersona\x12\x1d.persona.UpdatePersonaRequest\x1a\x1e.persona.UpdatePersonaResponse\x12N\n" +
	"\rDeletePersona\x12\x1d.persona.DeletePersonaRequest\x1a\x1e.persona.DeletePersonaResponseB3Z1github.com/fr0g-vibe/fr0g-ai-aip/internal/grpc/pbb\x06proto3"

var (
	file_proto_persona_proto_rawDescOnce sync.Once
	file_proto_persona_proto_rawDescData []byte
)

func file_proto_persona_proto_rawDescGZIP() []byte {
	file_proto_persona_proto_rawDescOnce.Do(func() {
		file_proto_persona_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_persona_proto_rawDesc), len(file_proto_persona_proto_rawDesc)))
	})
	return file_proto_persona_proto_rawDescData
}

var file_proto_persona_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_persona_proto_goTypes = []any{
	(*Persona)(nil),               // 0: persona.Persona
	(*CreatePersonaRequest)(nil),  // 1: persona.CreatePersonaRequest
	(*GetPersonaRequest)(nil),     // 2: persona.GetPersonaRequest
	(*DeletePersonaRequest)(nil),  // 3: persona.DeletePersonaRequest
	(*ListPersonasRequest)(nil),   // 4: persona.ListPersonasRequest
	(*UpdatePersonaRequest)(nil),  // 5: persona.UpdatePersonaRequest
	(*CreatePersonaResponse)(nil), // 6: persona.CreatePersonaResponse
	(*GetPersonaResponse)(nil),    // 7: persona.GetPersonaResponse
	(*DeletePersonaResponse)(nil), // 8: persona.DeletePersonaResponse
	(*ListPersonasResponse)(nil),  // 9: persona.ListPersonasResponse
	(*UpdatePersonaResponse)(nil), // 10: persona.UpdatePersonaResponse
	nil,                           // 11: persona.Persona.ContextEntry
}
var file_proto_persona_proto_depIdxs = []int32{
	11, // 0: persona.Persona.context:type_name -> persona.Persona.ContextEntry
	0,  // 1: persona.CreatePersonaRequest.persona:type_name -> persona.Persona
	0,  // 2: persona.UpdatePersonaRequest.persona:type_name -> persona.Persona
	0,  // 3: persona.CreatePersonaResponse.persona:type_name -> persona.Persona
	0,  // 4: persona.GetPersonaResponse.persona:type_name -> persona.Persona
	0,  // 5: persona.ListPersonasResponse.personas:type_name -> persona.Persona
	0,  // 6: persona.UpdatePersonaResponse.persona:type_name -> persona.Persona
	1,  // 7: persona.PersonaService.CreatePersona:input_type -> persona.CreatePersonaRequest
	2,  // 8: persona.PersonaService.GetPersona:input_type -> persona.GetPersonaRequest
	4,  // 9: persona.PersonaService.ListPersonas:input_type -> persona.ListPersonasRequest
	5,  // 10: persona.PersonaService.UpdatePersona:input_type -> persona.UpdatePersonaRequest
	3,  // 11: persona.PersonaService.DeletePersona:input_type -> persona.DeletePersonaRequest
	6,  // 12: persona.PersonaService.CreatePersona:output_type -> persona.CreatePersonaResponse
	7,  // 13: persona.PersonaService.GetPersona:output_type -> persona.GetPersonaResponse
	9,  // 14: persona.PersonaService.ListPersonas:output_type -> persona.ListPersonasResponse
	10, // 15: persona.PersonaService.UpdatePersona:output_type -> persona.UpdatePersonaResponse
	8,  // 16: persona.PersonaService.DeletePersona:output_type -> persona.DeletePersonaResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_persona_proto_init() }
func file_proto_persona_proto_init() {
	if File_proto_persona_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_persona_proto_rawDesc), len(file_proto_persona_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_persona_proto_goTypes,
		DependencyIndexes: file_proto_persona_proto_depIdxs,
		MessageInfos:      file_proto_persona_proto_msgTypes,
	}.Build()
	File_proto_persona_proto = out.File
	file_proto_persona_proto_goTypes = nil
	file_proto_persona_proto_depIdxs = nil
}
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: persona.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Persona represents an AI persona with specific expertise
type Persona struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Topic   string            `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Prompt  string            `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Context map[string]string `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Rag     []string          `protobuf:"bytes,6,rep,name=rag,proto3" json:"rag,omitempty"`
}

func (x *Persona) Reset() {
	*x = Persona{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persona_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Persona) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Persona) ProtoMessage() {}

func (x *Persona) ProtoReflect() protoreflect.Message {
	mi := &file_persona_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Persona.ProtoReflect.Descriptor instead.
func (*Persona) Descriptor() ([]byte, []int) {
	return file_persona_proto_rawDescGZIP(), []int{0}
}

func (x *Persona) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Persona) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Persona) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Persona) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Persona) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *Persona) GetRag() []string {
	if x != nil {
		return x.Rag
	}
	return nil
}

// Request messages
type CreatePersonaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Persona *Persona `protobuf:"bytes,1,opt,name=persona,proto3" json:"persona,omitempty"`
}

func (x *CreatePersonaRequest) Reset() {
	*x = CreatePersonaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persona_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonaRequest) ProtoMessage() {}

func (x *CreatePersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_persona_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonaRequest.ProtoReflect.Descriptor instead.
func (*CreatePersonaRequest) Descriptor() ([]byte, []int) {
	return file_persona_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePersonaRequest) GetPersona() *Persona {
	if x != nil {
		return x.Persona
	}
	return nil
}

type GetPersonaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPersonaRequest) Reset() {
	*x = GetPersonaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persona_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonaRequest) ProtoMessage() {}

func (x *GetPersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_persona_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonaRequest.ProtoReflect.Descriptor instead.
func (*GetPersonaRequest) Descriptor() ([]byte, []int) {
	return file_persona_proto_rawDescGZIP(), []int{2}
}

func (x *GetPersonaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePersonaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePersonaRequest) Reset() {
	*x = DeletePersonaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persona_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonaRequest) ProtoMessage() {}

func (x *DeletePersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_persona_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonaRequest.ProtoReflect.Descriptor instead.
func (*DeletePersonaRequest) Descriptor() ([]byte, []int) {
	return file_persona_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePersonaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPersonasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPersonasRequest) Reset() {
	*x = ListPersonasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persona_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPersonasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonasRequest) ProtoMessage() {}

func (x *ListPersonasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_persona_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonasRequest.ProtoReflect.Descriptor instead.
func (*ListPersonasRequest) Descriptor() ([]byte, []int) {
	return file_persona_proto_rawDescGZIP(), []int{4}
}

type UpdatePersonaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Persona *Persona `protobuf:"bytes,2,opt,name=persona,proto3" json:"persona,omitempty"`
}

func (x *UpdatePersonaRequest) Reset() {
	*x = UpdatePersonaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persona_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePersonaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonaRequest) ProtoMessage() {}

func (x *UpdatePersonaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_persona_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonaRequest.ProtoReflect.Descriptor instead.
func (*UpdatePersonaRequest) Descriptor() ([]byte, []int) {
	return file_persona_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePersonaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePersonaRequest) GetPersona() *Persona {
	if x != nil {
		return x.Persona
	}
	return nil
}

// Response messages
type CreatePersonaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Persona *Persona `protobuf:"bytes,1,opt,name=persona,proto3" json:"persona,omitempty"`
}

func (x *CreatePersonaResponse) Reset() {
	*x = CreatePersonaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persona_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePersonaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePersonaResponse) ProtoMessage() {}

func (x *CreatePersonaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_persona_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePersonaResponse.ProtoReflect.Descriptor instead.
func (*CreatePersonaResponse) Descriptor() ([]byte, []int) {
	return file_persona_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePersonaResponse) GetPersona() *Persona {
	if x != nil {
		return x.Persona
	}
	return nil
}

type GetPersonaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Persona *Persona `protobuf:"bytes,1,opt,name=persona,proto3" json:"persona,omitempty"`
}

func (x *GetPersonaResponse) Reset() {
	*x = GetPersonaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persona_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPersonaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonaResponse) ProtoMessage() {}

func (x *GetPersonaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_persona_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonaResponse.ProtoReflect.Descriptor instead.
func (*GetPersonaResponse) Descriptor() ([]byte, []int) {
	return file_persona_proto_rawDescGZIP(), []int{7}
}

func (x *GetPersonaResponse) GetPersona() *Persona {
	if x != nil {
		return x.Persona
	}
	return nil
}

type DeletePersonaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePersonaResponse) Reset() {
	*x = DeletePersonaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persona_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePersonaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePersonaResponse) ProtoMessage() {}

func (x *DeletePersonaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_persona_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePersonaResponse.ProtoReflect.Descriptor instead.
func (*DeletePersonaResponse) Descriptor() ([]byte, []int) {
	return file_persona_proto_rawDescGZIP(), []int{8}
}

type ListPersonasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Personas []*Persona `protobuf:"bytes,1,rep,name=personas,proto3" json:"personas,omitempty"`
}

func (x *ListPersonasResponse) Reset() {
	*x = ListPersonasResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persona_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPersonasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPersonasResponse) ProtoMessage() {}

func (x *ListPersonasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_persona_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPersonasResponse.ProtoReflect.Descriptor instead.
func (*ListPersonasResponse) Descriptor() ([]byte, []int) {
	return file_persona_proto_rawDescGZIP(), []int{9}
}

func (x *ListPersonasResponse) GetPersonas() []*Persona {
	if x != nil {
		return x.Personas
	}
	return nil
}

type UpdatePersonaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Persona *Persona `protobuf:"bytes,1,opt,name=persona,proto3" json:"persona,omitempty"`
}

func (x *UpdatePersonaResponse) Reset() {
	*x = UpdatePersonaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_persona_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePersonaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePersonaResponse) ProtoMessage() {}

func (x *UpdatePersonaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_persona_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePersonaResponse.ProtoReflect.Descriptor instead.
func (*UpdatePersonaResponse) Descriptor() ([]byte, []int) {
	return file_persona_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePersonaResponse) GetPersona() *Persona {
	if x != nil {
		return x.Persona
	}
	return nil
}

var File_persona_proto protoreflect.FileDescriptor

var file_persona_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x22, 0xd8, 0x01, 0x0a, 0x07, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x37, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x61, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x61, 0x67, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x72, 0x61,
	0x67, 0x1a, 0x3a, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x42, 0x0a,
	0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x61, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x15,
	0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x56, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a,
	0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x22, 0x43, 0x0a, 0x15, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x2e, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x22, 0x40,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x2e,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x46, 0x0a, 0x14, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x2e, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x08, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x73, 0x22,
	0x43, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x07, 0x70, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x61, 0x32, 0xb8, 0x02, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x12, 0x1d, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x12, 0x1a, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47,
	0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x73, 0x12, 0x1c,
	0x2e, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x12, 0x1d, 0x2e, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x12, 0x1d, 0x2e, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x72, 0x30, 0x67, 0x2d, 0x76,
	0x69, 0x62, 0x65, 0x2f, 0x66, 0x72, 0x30, 0x67, 0x2d, 0x61, 0x69, 0x2d, 0x61, 0x69, 0x70, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_persona_proto_rawDescOnce sync.Once
	file_persona_proto_rawDescData = file_persona_proto_rawDesc
)

func file_persona_proto_rawDescGZIP() []byte {
	file_persona_proto_rawDescOnce.Do(func() {
		file_persona_proto_rawDescData = protoimpl.X.CompressGZIP(file_persona_proto_rawDescData)
	})
	return file_persona_proto_rawDescData
}

var file_persona_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_persona_proto_goTypes = []interface{}{
	(*Persona)(nil),                // 0: persona.Persona
	(*CreatePersonaRequest)(nil),   // 1: persona.CreatePersonaRequest
	(*GetPersonaRequest)(nil),      // 2: persona.GetPersonaRequest
	(*DeletePersonaRequest)(nil),   // 3: persona.DeletePersonaRequest
	(*ListPersonasRequest)(nil),    // 4: persona.ListPersonasRequest
	(*UpdatePersonaRequest)(nil),   // 5: persona.UpdatePersonaRequest
	(*CreatePersonaResponse)(nil),  // 6: persona.CreatePersonaResponse
	(*GetPersonaResponse)(nil),     // 7: persona.GetPersonaResponse
	(*DeletePersonaResponse)(nil),  // 8: persona.DeletePersonaResponse
	(*ListPersonasResponse)(nil),   // 9: persona.ListPersonasResponse
	(*UpdatePersonaResponse)(nil),  // 10: persona.UpdatePersonaResponse
	nil,                            // 11: persona.Persona.ContextEntry
}
var file_persona_proto_depIdxs = []int32{
	11, // 0: persona.Persona.context:type_name -> persona.Persona.ContextEntry
	0,  // 1: persona.CreatePersonaRequest.persona:type_name -> persona.Persona
	0,  // 2: persona.UpdatePersonaRequest.persona:type_name -> persona.Persona
	0,  // 3: persona.CreatePersonaResponse.persona:type_name -> persona.Persona
	0,  // 4: persona.GetPersonaResponse.persona:type_name -> persona.Persona
	0,  // 5: persona.ListPersonasResponse.personas:type_name -> persona.Persona
	0,  // 6: persona.UpdatePersonaResponse.persona:type_name -> persona.Persona
	1,  // 7: persona.PersonaService.CreatePersona:input_type -> persona.CreatePersonaRequest
	2,  // 8: persona.PersonaService.GetPersona:input_type -> persona.GetPersonaRequest
	4,  // 9: persona.PersonaService.ListPersonas:input_type -> persona.ListPersonasRequest
	5,  // 10: persona.PersonaService.UpdatePersona:input_type -> persona.UpdatePersonaRequest
	3,  // 11: persona.PersonaService.DeletePersona:input_type -> persona.DeletePersonaRequest
	6,  // 12: persona.PersonaService.CreatePersona:output_type -> persona.CreatePersonaResponse
	7,  // 13: persona.PersonaService.GetPersona:output_type -> persona.GetPersonaResponse
	9,  // 14: persona.PersonaService.ListPersonas:output_type -> persona.ListPersonasResponse
	10, // 15: persona.PersonaService.UpdatePersona:output_type -> persona.UpdatePersonaResponse
	8,  // 16: persona.PersonaService.DeletePersona:output_type -> persona.DeletePersonaResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_persona_proto_init() }
func file_persona_proto_init() {
	if File_persona_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_persona_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Persona); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_persona_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePersonaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_persona_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPersonaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_persona_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePersonaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_persona_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPersonasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_persona_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePersonaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_persona_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePersonaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_persona_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPersonaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_persona_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePersonaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_persona_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPersonasResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_persona_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePersonaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_persona_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_persona_proto_goTypes,
		DependencyIndexes: file_persona_proto_depIdxs,
		MessageInfos:      file_persona_proto_msgTypes,
	}.Build()
	File_persona_proto = out.File
	file_persona_proto_rawDesc = nil
	file_persona_proto_goTypes = nil
}
